In [1]:
import numpy as np


#加载数据
def load_data():
    with open('约会数据.txt') as fr:
        lines = fr.readlines()

    x = np.empty((len(lines), 3), dtype=float)
    y = np.empty(len(lines), dtype=int)

    for i in range(len(lines)):
        line = lines[i].strip().split('\t')
        x[i] = line[:3]
        y[i] = line[3]
    return x, y


x, y = load_data()
x, y

(array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01],
        [1.4488000e+04, 7.1534690e+00, 1.6739040e+00],
        [2.6052000e+04, 1.4418710e+00, 8.0512400e-01],
        ...,
        [2.6575000e+04, 1.0650102e+01, 8.6662700e-01],
        [4.8111000e+04, 9.1345280e+00, 7.2804500e-01],
        [4.3757000e+04, 7.8826010e+00, 1.3324460e+00]]),
 array([3, 2, 1, 1, 1, 1, 3, 3, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 2, 1,
        2, 3, 2, 3, 2, 3, 2, 1, 3, 1, 3, 1, 2, 1, 1, 2, 3, 3, 1, 2, 3, 3,
        3, 1, 1, 1, 1, 2, 2, 1, 3, 2, 2, 2, 2, 3, 1, 2, 1, 2, 2, 2, 2, 2,
        3, 2, 3, 1, 2, 3, 2, 2, 1, 3, 1, 1, 3, 3, 1, 2, 3, 1, 3, 1, 2, 2,
        1, 1, 3, 3, 1, 2, 1, 3, 3, 2, 1, 1, 3, 1, 2, 3, 3, 2, 3, 3, 1, 2,
        3, 2, 1, 3, 1, 2, 1, 1, 2, 3, 2, 3, 2, 3, 2, 1, 3, 3, 3, 1, 3, 2,
        2, 3, 1, 3, 3, 3, 1, 3, 1, 1, 3, 3, 2, 3, 3, 1, 2, 3, 2, 2, 3, 3,
        3, 1, 2, 2, 1, 1, 3, 2, 3, 3, 1, 2, 1, 3, 1, 2, 3, 2, 3, 1, 1, 1,
        3, 2, 3, 1, 3, 2, 1, 3, 2, 2, 3, 2, 3, 2, 1, 1, 3, 1, 3

In [2]:
#数据归一化
def norm():
    #这里是按列统计的
    x_col_min = x.min(axis=0)
    x_col_max = x.max(axis=0)

    #这一步之后,最小值是0
    x_norm = x - x_col_min

    #这一步之后,最大值是1
    x_norm /= x_col_max - x_col_min
    return x_norm


x = norm()
x

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [3]:
#切分数据集

test_x = x[900:]
test_y = y[900:]

x = x[:900]
y = y[:900]

test_x.shape, test_y.shape, x.shape, y.shape

((100, 3), (100,), (900, 3), (900,))

In [4]:
def knn(_x, k=3):
    temp = _x - x
    temp = np.power(temp, 2)
    temp = temp.sum(axis=1)
    temp = np.sqrt(temp)
    argsort = temp.argsort()

    result = y[argsort][:k]
    return np.bincount(result).argmax()


knn(test_x[0], k=11)

1

In [5]:
correct = 0
for i in range(len(test_x)):
    pred = knn(test_x[i], k=5)
    #print(pred, test_y[i])

    if pred == test_y[i]:
        correct += 1

print(correct / len(test_x))

0.95
